/**
 * components/ui/EmailModal.jsx
 * -----------------------------
 * Modal for sending dashboard report via Gmail (n8n webhook).
 */
"use client";
import { useState } from "react";
import { sendEmailReport } from "@/services/n8n";

export default function EmailModal({ onClose, dashboard, question }) {
  const [to, setTo] = useState("");
  const [subject, setSubject] = useState(`Dashboard Report: ${question || "AI BI Analysis"}`);
  const [status, setStatus] = useState(null); // null | "loading" | "success" | "error"
  const [errorMsg, setErrorMsg] = useState("");

  const buildBody = () => {
    if (!dashboard) return "Please find the dashboard report attached.";
    const kpiText = (dashboard.kpis || []).map(k => `• ${k.label}: ${k.value}`).join("\n");
    const insightText = (dashboard.insights || []).map(i => `• ${i}`).join("\n");
    return `📊 Dashboard Report\n\nQuestion: ${question}\n\n📌 Key Metrics:\n${kpiText}\n\n🤖 AI Insights:\n${insightText}\n\n📝 Summary:\n${dashboard.summary || ""}\n\nGenerated by AI BI Dashboard`;
  };

  const handleSend = async () => {
    if (!to.trim() || !to.includes("@")) {
      setErrorMsg("Please enter a valid email address.");
      return;
    }
    setStatus("loading");
    setErrorMsg("");
    try {
      const kpis = dashboard?.kpis || [];
      const chartSummary = (dashboard?.all_charts || []).map(c => c.title).join(", ");
      await sendEmailReport({ to: to.trim(), subject, body: buildBody(), chartSummary, kpis });
      setStatus("success");
    } catch (err) {
      setStatus("error");
      setErrorMsg(err.message || "Failed to send email.");
    }
  };

  return (
    <div className="fixed inset-0 bg-black/40 backdrop-blur-sm z-50 flex items-center justify-center p-4">
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-md p-6 space-y-4">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <span className="text-2xl">📧</span>
            <h2 className="text-base font-bold text-gray-800">Send Email Report</h2>
          </div>
          <button onClick={onClose} className="text-gray-400 hover:text-gray-600 text-xl">✕</button>
        </div>

        {status === "success" ? (
          <div className="text-center py-8 space-y-3">
            <div className="text-5xl">✅</div>
            <p className="text-green-700 font-semibold">Email sent successfully!</p>
            <p className="text-xs text-gray-500">Check your inbox at <strong>{to}</strong></p>
            <button onClick={onClose}
              className="mt-2 px-4 py-2 bg-indigo-600 text-white text-sm rounded-lg hover:bg-indigo-700">
              Close
            </button>
          </div>
        ) : (
          <>
            {/* To field */}
            <div className="space-y-1">
              <label className="text-xs font-semibold text-gray-600">To (Email Address)</label>
              <input type="email" value={to} onChange={e => setTo(e.target.value)}
                placeholder="example@gmail.com"
                className="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-300" />
            </div>

            {/* Subject field */}
            <div className="space-y-1">
              <label className="text-xs font-semibold text-gray-600">Subject</label>
              <input type="text" value={subject} onChange={e => setSubject(e.target.value)}
                className="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-300" />
            </div>

            {/* Preview */}
            <div className="space-y-1">
              <label className="text-xs font-semibold text-gray-600">Email Preview</label>
              <div className="bg-gray-50 border border-gray-100 rounded-lg p-3 text-xs text-gray-600 whitespace-pre-wrap max-h-36 overflow-y-auto font-mono">
                {buildBody()}
              </div>
            </div>

            {/* Error */}
            {errorMsg && (
              <p className="text-xs text-red-600 bg-red-50 border border-red-200 rounded-lg px-3 py-2">
                ⚠️ {errorMsg}
              </p>
            )}

            {/* Buttons */}
            <div className="flex gap-2 pt-1">
              <button onClick={onClose}
                className="flex-1 px-4 py-2 text-sm border border-gray-200 rounded-lg hover:bg-gray-50">
                Cancel
              </button>
              <button onClick={handleSend} disabled={status === "loading"}
                className="flex-1 px-4 py-2 text-sm bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 disabled:opacity-50 flex items-center justify-center gap-2">
                {status === "loading" ? (
                  <><span className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />Sending...</>
                ) : (
                  <><span>📤</span> Send Report</>
                )}
              </button>
            </div>
          </>
        )}
      </div>
    </div>
  );
}
